// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7U85haWD5zRdqNHwortqHIXLfoRlpil4',
    appId: '1:998471968632:web:99de550727ed8bb251ca8d',
    messagingSenderId: '998471968632',
    projectId: 'lab3-2d86e',
    authDomain: 'lab3-2d86e.firebaseapp.com',
    storageBucket: 'lab3-2d86e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtsGa76Peaajn_4Sux9Ps3Q7e99Dw59cA',
    appId: '1:998471968632:android:35ac8adc55797cc851ca8d',
    messagingSenderId: '998471968632',
    projectId: 'lab3-2d86e',
    storageBucket: 'lab3-2d86e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmUy7eNlDPZUkgDlhLf2tAo0-oZoYcdis',
    appId: '1:998471968632:ios:99f2a7f1ff10cbbe51ca8d',
    messagingSenderId: '998471968632',
    projectId: 'lab3-2d86e',
    storageBucket: 'lab3-2d86e.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmUy7eNlDPZUkgDlhLf2tAo0-oZoYcdis',
    appId: '1:998471968632:ios:99f2a7f1ff10cbbe51ca8d',
    messagingSenderId: '998471968632',
    projectId: 'lab3-2d86e',
    storageBucket: 'lab3-2d86e.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7U85haWD5zRdqNHwortqHIXLfoRlpil4',
    appId: '1:998471968632:web:5e9ebe765293858251ca8d',
    messagingSenderId: '998471968632',
    projectId: 'lab3-2d86e',
    authDomain: 'lab3-2d86e.firebaseapp.com',
    storageBucket: 'lab3-2d86e.firebasestorage.app',
  );
}
